<?php
namespace MyOrdersVault\Core;

// Builds a link back to the source email in Gmail. Deliberately uses a
// #search/ link rather than #all/<threadId>: on iOS, Safari intercepts
// mail.google.com links with a "Open in Gmail?" prompt, and neither
// choice honors the #all/<id> fragment — both just land on the inbox.
// #search/ is the one fragment format both Safari and the Gmail app
// reliably resolve to (a search results list, not the message itself).
//
// Gmail's own web URLs auto-open a message via a THIRD id segment after
// the query (#search/<query>/<webId>) — but that <webId> (e.g.
// "FMfcgzQZTCrjRRfGpVWqWfzWWcxGcWhL") is an opaque, per-account token
// generated by Gmail's own web client. It is NOT the Gmail API's
// thread_id/messageId, has no known derivation from API data, and can
// only be obtained by a human opening the message in a browser and
// copying the address bar. We only ever have the API-style IDs here, so
// appending those as a 3rd segment doesn't open the message — it can
// only confuse/break the plain search that otherwise works. Don't do it.
class GmailLink {
    private const FABRICATED_ORDER_NUMBER = '/^(GEN|PP)-[a-f0-9]{10}$/i';

    public static function build(?string $orderNumber, ?string $threadId, ?string $gmailMessageId): ?string
    {
        if (!empty($orderNumber) && !preg_match(self::FABRICATED_ORDER_NUMBER, $orderNumber)) {
            return 'https://mail.google.com/mail/u/0/#search/' . rawurlencode($orderNumber);
        }

        $targetId = $threadId ?: $gmailMessageId;
        if (!empty($targetId)) {
            return 'https://mail.google.com/mail/u/0/#all/' . rawurlencode($targetId);
        }

        return null;
    }
}
